ititgogo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'language/', include('language.urls')),
    url(r'shouce/', include('shouce.urls')),
    url(r'', include('tutorial.urls')),
]

language/urls.py
# coding:utf-8
from django.conf.urls import url 
from django.conf import settings
from .views import LanguageListView, LanguageDetailView

app_name = 'language'
urlpatterns = [
	url(r'^$', LanguageListView.as_view(), name='index'),
	url(r'^detail/(?P<language_id>\d+)/$', LanguageDetailView.as_view(), name='detail'),
]

shouce/urls.py
# coding:utf-8
from django.conf.urls import url 
from django.conf import settings
from .views import ShouceListView

app_name = 'shouce'
urlpatterns = [
	url(r'^$', ShouceListView.as_view(), name='index'),
]

tutorial/urls.py
# coding:utf-8
from django.conf.urls import url 
from .views import TutorialListView, TutorialDetailView

app_name = 'tutorial'
urlpatterns = [
	url(r'^$', TutorialListView.as_view(), name='index'),
	url(r'^tutorial/(?P<tutorial_id>\d+)/$', TutorialDetailView.as_view(), name='detail'),
]

language/models.py
# coding:utf-8
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
# Create your models here.



@python_2_unicode_compatible
class Language(models.Model):
	name = models.CharField(verbose_name='编程语言', max_length=100)
	ctime = models.DateTimeField(default=datetime.now, verbose_name='添加时间', null=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('language:detail', kwargs={'pk':self.pk})

	class Meta:
		verbose_name = '编程语言'
		verbose_name_plural = verbose_name



@python_2_unicode_compatible
class Framework(models.Model):
	name = models.CharField(verbose_name='框架', max_length=100)
	language = models.ForeignKey(Language)
	ctime = models.DateTimeField(default=datetime.now, verbose_name='添加时间', null=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = '框架'
		verbose_name_plural = verbose_name

shouce/models.py
# coding:utf-8
from __future__ import unicode_literals

import language


from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
# Create your models here.


@python_2_unicode_compatible
class Shouce(models.Model):
	name = models.CharField(verbose_name='手册名称', max_length=150)
	url = models.URLField(max_length=300, verbose_name='链接')
	language = models.ForeignKey('language.Language')
	desc = models.TextField(verbose_name='简介')
	ctime = models.DateTimeField(verbose_name='添加时间', null=True)

	def __str__(self):
		return self.name

	# def get_absolute_url(self):
	# 	return reverse('shouce:detail', kwargs={'pk':self.pk})

	class Meta:
		verbose_name = '手册'
		verbose_name_plural = verbose_name

tutorial/models.py
# coding:utf-8
from __future__ import unicode_literals

import language

from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
# from language.models import Language
# Create your models here.


@python_2_unicode_compatible
class Tutorial(models.Model):
	title = models.CharField(verbose_name='教程名称', max_length=150)
	language = models.ForeignKey('language.Language')
	desc = models.TextField(verbose_name='简介')
	ctime = models.DateTimeField(verbose_name='添加时间', null=True)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('tutorial:detail', kwargs={'pk':self.pk})

	class Meta:
		verbose_name = '教程指南'
		verbose_name_plural = verbose_name



@python_2_unicode_compatible
class Tutorial_item(models.Model):
	name = models.CharField(verbose_name='教程章节', max_length=150)
	tutorial = models.ForeignKey(Tutorial)
	content = models.TextField(verbose_name='章节内容')
	ctime = models.DateTimeField(verbose_name='添加时间', null=True)


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('tutorial:item', kwargs={'pk':self.pk})

	class Meta:
		verbose_name = '教程章节'
		verbose_name_plural = verbose_name	

language/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Language, Framework
from django.views.generic.base import View
# Create your views here.


class LanguageListView(View):
	def get(self, request):
		all_language = Language.objects.all().order_by('-ctime')

		return render(request, 'language/index.html',{
			'all_language': all_language,
		})




class LanguageDetailView(View):
	def get(self, request, language_id):
		language = Language.objects.get(id=int(language_id))
		

		return render(request, 'language/detail.html', {
			'language': language,
		})

shouce/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Shouce
from django.views.generic.base import View
# Create your views here.


class ShouceListView(View):
	def get(self, request):
		all_shouce = Shouce.objects.all().order_by('-ctime')

		return render(request, 'shouce/index.html',{
			'all_shouce': all_shouce,
		})

tutorial/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Tutorial, Tutorial_item
from django.views.generic.base import View
# Create your views here.


class TutorialListView(View):
	def get(self, request):
		all_tutorials = Tutorial.objects.all().order_by('-ctime')

		return render(request, 'tutorial/index.html',{
			'all_tutorials':all_tutorials,
		})




class TutorialDetailView(View):
	def get(self, request, tutorial_id):
		tutorial = Tutorial.objects.get(id=int(tutorial_id))
		tutorial_item = Tutorial_item.objects.get(id=int(tutorial_id))
		

		return render(request, 'tutorial/detail.html', {
			'tutorial': tutorial,
			'tutorial_item':tutorial,
		})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %} - 编程社区</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="#">
	<script src="https://cdn.bootcss.com/jquery/3.2.1/core.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	{% block head %}{% endblock %}
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'tutorial:index' %}">编程社区</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	      <ul class="nav navbar-nav navbar-right">
		        <li><a href="{% url 'language:index' %}">语言</a></li>
		        <li><a href="{% url 'tutorial:index' %}">教程</a></li>
		        <li><a href="{% url 'shouce:index' %}">手册</a></li>
					
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="main">
		{% block main %}{% endblock %}
	</div>


</body>
</html>

templates/language/detail.html
{% extends 'base.html' %}
{% block title %}编程语言{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		
			<li>
				<a href="#">{{ language.name }}-3</a>
				<span>Framework.name</span>

			</li>
		
	</ul>

{% endblock %}

templates/language/index.html
{% extends 'base.html' %}
{% block title %}编程语言{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		{% for language in all_language %}
			<li>
				<a href="{% url 'language:detail' language.id %}">{{ language.name }}</a>
			</li>
		{% empty %}
			<div class="no-language">暂时还未填写语言</div>
		{% endfor %}
	</ul>

{% endblock %}

templates/shouce/index.html
{% extends 'base.html' %}
{% block title %}手册{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		{% for shouce in all_shouce %}
			<li>
				<a href="{{ shouce.url }}" target="_blank">{{ shouce.name }}</a>
			</li>
			<p>{{ shouce.desc }}</p>
		{% empty %}
			<div class="no-language">暂时还未填写语言</div>
		{% endfor %}
	</ul>

{% endblock %}

templates/tutorial/detail.html
{% extends 'base.html' %}
{% block title %}学习指南详细{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		
			<li>
				<a href="#">{{ tutorial.title }}-3</a>
				<span>Framework.name</span>

			</li>
		
	</ul>

{% endblock %}

templates/tutorial/index.html
{% extends 'base.html' %}
{% block title %}学习指南{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		{% for tutorial in all_tutorials %}
			<li>
				<a href="{% url 'tutorial:detail' tutorial.id %}">{{ tutorial.title }}</a>
			</li>
		{% empty %}
			<div class="no-tutorial">暂时还未填写语言</div>
		{% endfor %}
	</ul>

{% endblock %}